apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
spec:
  replicas: 1  # Number of running pods
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: williamwg/nodejs-app:latest  # Replace with your Docker Hub image
        imagePullPolicy:"Always"
        ports:
        - containerPort: 3000
